name: '3dbionotes-ruby'
services:
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWD}
    volumes:
      - dbdata:/var/lib/mysql
    expose:
      - "3306"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  # Data Base web interface
  # used during development for easy access to tables and data
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "${PMA_EXT_PORT}:80"
    depends_on:
            db:
                condition: service_healthy

  web:
    container_name: web-ruby
    tty: true
    command: 
      - bash
      - -c
      - |
        RAILS_ENV=production bundle exec rake db:migrate &&
        RAILS_ENV=production bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db
    volumes:
      - ${APP_BASE_PATH}:/services/bionotes
      - ${APP_DATABASES_PATH}:/services/bionotes/databases
      - ${BLAST_BIN}:/external/ncbi-blast
      - ${BLAST_DATABASE}:/external/db-blast
      - public-assets:/app/public
    expose:
      - "3000"
  
  # Web server for precompiled assets
  nginx:
    image: nginx:1.25
    container_name: nginx-ruby
    depends_on:
      - web
    command:
      - bash
      - -c
      - |
        sed "s/__BWS_API_PORT__/${BWS_API_PORT}/g; s/__LRS_API_PORT__/${LRS_API_PORT}/g" /etc/nginx/nginx.conf.template > /tmp/nginx.conf &&
        nginx -c /tmp/nginx.conf -g 'daemon off;'
    ports:
      - "${APP_EXT_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
      - public-assets:/app/public:ro
    environment:
      - NGINX_PORT=80
      - BWS_API_PORT=${BWS_API_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  dbdata: null