name: "3dbionotes-ruby"
services:
    # Data Base
    db:
        image: mysql:8.0
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWD}
        volumes:
            - dbdata:/var/lib/mysql
        expose:
            - "3306"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
        networks:
            - bnts-network

    # Data Base web interface used during development for easy access to tables and data
    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_PORT: ${DB_PORT}
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "${PMA_EXT_PORT}:80"
        depends_on:
            db:
                condition: service_healthy
        networks:
            - bnts-network

    # Ruby on Rails
    web:
        image: ${IMAGE_NAME}
        build:
            context: .
        env_file: .env
        container_name: web-ruby
        tty: true
        command:
            - bash
            - -c
            - |
                RAILS_ENV=development bundle exec rake db:migrate &&
                RAILS_ENV=development bundle exec rails s -p 3000 -b '0.0.0.0'
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - bionotes-root:/services/bionotes
            - bionotes-data:/services/bionotes/apps/bionotes/data
            - bionotes-db:/services/bionotes/apps/bionotes/db
            - bionotes-upload:/services/bionotes/apps/bionotes/public/upload
            - bionotes-databases:/services/bionotes/databases
            - public-assets:/app/public
            - .:/services/bionotes/apps/bionotes
        expose:
            - "3000"
        networks:
            - bnts-network

    # Web server for precompiled assets
    nginx:
        image: nginx:1.25
        container_name: nginx-ruby
        depends_on:
            - web
        ports:
            - "${APP_EXT_PORT}:80"
        volumes:
            - ./nginx/dev.conf.template:/etc/nginx/templates/default.conf.template:ro
            - public-assets:/app/public:ro
        environment:
            - NGINX_PORT=80
        networks:
            - bnts-network

volumes:
    dbdata: null
    public-assets:
    bionotes-root:
    bionotes-data:
    bionotes-upload:
    bionotes-db:
    bionotes-databases:

networks:
    bnts-network:
        driver: bridge
