name: "3dbionotes-web"
#
# COMMON ONLY SETTINGS
#
services:
  # Web Application
  web:
    image: ${IMAGE_NAME}
    build:
      context: .
    env_file: .env
    ports:
      - "${APP_EXT_PORT}:3000"

  # Data Base
  db:
    image: mysql:8.0
    container_name: db
    command:
      # - '--local_infile=1' in development
      - '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWD}
    volumes:
      - dbdata:/var/lib/mysql
      - ${DB_EXT_DBS}:/media/databases
    expose:
      - "3306"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  # blast:
  #   image: ncbi/blast
  #   command: "/bin/bash"
  #   deploy:
  #       restart_policy:
  #         condition: on-failure
  #         delay: 5s
  #         max_attempts: 3
  #         window: 120s
  #   volumes:
  #     - ${BLAST_DB}:/blast/blastdb
  #     - ${BLAST_DB_CUSTOM}:/blast/blastdb_custom
  #     - ${BLAST_QUERIES}:/blast/queries
  #     - ${BLAST_RESULTS}:/blast/results
  #   networks:
  #     - bnts-nw


volumes:
  dbdata: null


networks:
  bnts-nw:
    name: ${APP_NETWORK_NAME}
    external: true